# Generated by Django 3.1.1 on 2020-09-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='is_premium',
        ),
        migrations.AddField(
            model_name='store',
            name='photo',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
