# Generated by Django 3.1.1 on 2020-09-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200905_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_premium',
            field=models.BooleanField(null=True),
        ),
    ]
