# Generated by Django 3.1.1 on 2020-09-05 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_store_is_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='photo',
        ),
    ]
