# Generated by Django 3.1.1 on 2020-09-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_store_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='photo',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
