# Generated by Django 3.1.1 on 2020-09-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_store_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='latitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='longitude',
            field=models.IntegerField(null=True),
        ),
    ]
