# Generated by Django 3.1.1 on 2020-09-04 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, null=True)),
                ('phone', models.CharField(max_length=45, null=True)),
                ('marketing_email', models.BooleanField()),
                ('marketing_sms', models.BooleanField()),
                ('barcode', models.IntegerField()),
                ('purchasing_type', models.IntegerField(null=True)),
                ('auto_extension', models.BooleanField()),
                ('locality', models.IntegerField()),
                ('recent_search_keywords', models.CharField(max_length=45, null=True)),
                ('recent_viewed', models.CharField(max_length=45, null=True)),
                ('profile', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('birthday', models.DateTimeField(null=True)),
                ('sex', models.BooleanField()),
                ('certified', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
