# Generated by Django 3.1.1 on 2020-09-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='auto_extension',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='barcode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='birthday',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='certified',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='locality',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='marketing_email',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='marketing_sms',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
