# Generated by Django 2.1.1 on 2020-09-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200912_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='menu',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
